name: Publish

on:
  workflow_dispatch:
    inputs:
      maven_username:
        required: true
        description: 'Your blucobalt.dev Maven username.'
        default: 'halotroop2288'
      maven_password:
        required: true
        description: 'Your blucobalt.dev Maven password'
        default: ''

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Adoptium JDK 16
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 16
          distribution: adopt
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Publish to Maven
        run: ./gradlew publish
        env:
          MAVEN_PUBLISH_TOKEN: ${{ secrets.TOKEN }}
          maven_username: ${{ github.input.event.maven_username }}
          maven_password: ${{ github.input.event.maven_password }}
