name: Build and Publish
on: [push]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Adoptium Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build Number Generator
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Publish to Maven Local and test conflicts
        run: ./gradlew publishToMavenLocal --stacktrace
      - run: cd test-mod && ./gradlew build
      - name: Publish to Maven
        run: ./gradlew publish --stacktrace
        env:
          MAVEN_URL: "https://repo.blucobalt.dev/repository/maven-halotroop"
          MAVEN_USERNAME: ${{ github.event.inputs.maven_username }}
          MAVEN_PASSWORD: ${{ github.event.inputs.maven_password }}
