name: Build and Publish
on:
  workflow_dispatch:
  
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Adoptium Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Publish to Maven Local and test conflicts
        run: ./gradlew publishToMavenLocal --stacktrace
      - run: cd test-mod && ./gradlew build genSources
      - name: Publish to Maven
        run: ./gradlew publish --stacktrace
        env:
          MAVEN_PUBLISH_CREDENTIALS: ${{ secrets.MAVEN_PUBLISH_CREDENTIALS }}
