name: Publish

on:
  workflow_dispatch:
    inputs:
      maven_username:
        required: true
        description: 'Your blucobalt.dev Maven username.'
        default: 'halotroop2288'
      maven_password:
        required: true
        description: 'Your blucobalt.dev Maven password'
        default: ''

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Adoptium Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build Number Generator
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Publish to Maven
        run: ./gradlew publish
        env:
          MAVEN_PUBLISH_TOKEN: ${{ secrets.TOKEN }}
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}
          MAVEN_USERNAME: ${{ github.input.event.maven_username }}
          MAVEN_PASSWORD: ${{ github.input.event.maven_password }}
